version: "3.9"
services:
  storybook:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6006:6006
    volumes:
      - ./lvup-fe/services/lvup/public:/home/node/storybook/public
      - ./lvup-fe/services/lvup/src:/home/node/storybook/services/lvup/src
      - ./lvup-fe/shared:/home/node/storybook/shared
      - ./.storybook:/home/node/storybook/.storybook
      - ./stories:/home/node/storybook/stories
      - ./unit-test:/home/node/storybook/unit-test
#      - ./jest.config.js:/home/node/storybook/jest.config.js